# Generated by Django 3.2.6 on 2021-10-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer1', models.IntegerField(blank=True, verbose_name='answer1')),
                ('answer2', models.IntegerField(blank=True, verbose_name='answer2')),
                ('answer3', models.IntegerField(blank=True, verbose_name='answer3')),
                ('answer4', models.IntegerField(blank=True, verbose_name='answer4')),
                ('answer5', models.IntegerField(blank=True, verbose_name='answer5')),
                ('answer6', models.IntegerField(blank=True, verbose_name='answer6')),
                ('answer7', models.IntegerField(blank=True, verbose_name='answer7')),
                ('answer8', models.IntegerField(blank=True, verbose_name='answer8')),
                ('answer9', models.IntegerField(blank=True, verbose_name='answer9')),
                ('answer10', models.IntegerField(blank=True, verbose_name='answer10')),
                ('answer11', models.IntegerField(blank=True, verbose_name='answer11')),
                ('answer12', models.IntegerField(blank=True, verbose_name='answer12')),
                ('answer13', models.IntegerField(blank=True, verbose_name='answer13')),
                ('answer14', models.IntegerField(blank=True, verbose_name='answer14')),
                ('answer15', models.IntegerField(blank=True, verbose_name='answer15')),
                ('answer16', models.IntegerField(blank=True, verbose_name='answer16')),
                ('answer17', models.IntegerField(blank=True, verbose_name='answer17')),
                ('answer18', models.IntegerField(blank=True, verbose_name='answer18')),
            ],
            options={
                'db_table': 'personality',
            },
        ),
    ]
